export { parseGameDefinition, parseVariantFile, validateMeta, produceDefinition } from './src/schema.js'
export { parseFrontmatter } from './src/parse-frontmatter.js'
export { validate } from './src/validate.js'
export { produce } from './src/produce.js'
export { produceLayout } from './src/produce-layout.js'
export { resolveSurface, BUILTIN_SURFACES } from './src/surfaces.js'
export { loadVariantFile, loadGameDefinition, loadFamily, loadAllFamilies, scanFrontmatter, loadEngineReady } from './src/loader.js'
export { inferTopology, inferPlayers, inferEngineBlock, generateEngineFrontmatter } from './src/infer.js'
export { enrichMeta, serializeFrontmatter, enrichFile, enrichDryRun } from './src/enrich.js'
export { resolve as cascadeResolve, deepMerge, deriveDefaults } from './src/cascade-resolver.js'
export { resolveRulesDir } from './src/rules-dir.js'
export { buildCrossMap } from './src/cross-map.js'
