export { createSimulator } from './src/simulator.js'
export { createMinimax, DIFFICULTIES } from './src/minimax.js'
export { createMCTS, MCTS_DIFFICULTIES } from './src/mcts.js'
export { createOpeningBook } from './src/opening-book.js'
export { EVALUATORS, registerEvaluator, getEvaluator } from './src/evaluators.js'
