const { test, expect } = require('@playwright/test')
const BASE = (process.env.BASE_URL || 'http://localhost:80/MODDABLE/moddable-engine') + '/play/'

// The status line under the board. The old board renderer had one; the
// interactive session never wired it up, so a player could see a piece and have
// no way to learn what it was called. Everything it says is read from the live
// position and the plugin's vocabulary - nothing is written down anywhere.
test.describe('board status line', () => {
  test('names the square and what is standing on it', async ({ page }) => {
    await page.goto(`${BASE}?family=chess&variant=congo&opponent=human`)
    await page.waitForSelector('#game-play-root [data-sq]', { timeout: 20000 })
    await page.waitForTimeout(1200)
    await page.locator('#game-play-root [data-sq="d1"]').first().hover()
    await expect(page.locator('#info-text')).toHaveText(/d1.*Lion/i)
    await page.locator('#game-play-root [data-sq="d4"]').first().hover()
    await expect(page.locator('#info-text')).toHaveText(/d4.*empty/i)
  })

  test('says what a square is to the piece already selected', async ({ page }) => {
    await page.goto(`${BASE}?family=chess&variant=congo&opponent=human`)
    await page.waitForSelector('#game-play-root [data-sq]', { timeout: 20000 })
    await page.waitForTimeout(1200)
    await page.locator('#game-play-root [data-sq="d2"]').first().click()
    await page.waitForTimeout(250)
    await page.locator('#game-play-root [data-sq="d3"]').first().hover()
    await expect(page.locator('#info-text')).toHaveText(/move here/i)
  })

  test('names pieces in a family that is not chess', async ({ page }) => {
    await page.goto(`${BASE}?family=shogi&variant=standard&opponent=human`)
    await page.waitForSelector('#game-play-root [data-sq]', { timeout: 20000 })
    await page.waitForTimeout(1200)
    const cells = await page.locator('#game-play-root [data-sq]').evaluateAll(
      els => els.map(e => e.getAttribute('data-sq')).filter(Boolean))
    let named = 0
    for (const sq of cells.slice(0, 30)) {
      await page.locator(`#game-play-root [data-sq="${sq}"]`).first().hover()
      const text = (await page.locator('#info-text').textContent()) || ''
      if (/·/.test(text) && !/empty/.test(text)) named += 1
    }
    expect(named).toBeGreaterThan(0)
  })
})

// The piece legend. Every entry is generated by asking the engine what the
// piece can do from a real square, so it cannot drift from the rules; a piece
// whose moves cannot be shown is left out rather than drawn as one that cannot
// move.
test.describe('piece legend', () => {
  test('lists exactly the pieces the variant has, with real moves', async ({ page }) => {
    await page.goto(`${BASE}?family=chess&variant=congo&opponent=human`)
    await page.waitForSelector('#game-play-root [data-sq]', { timeout: 20000 })
    await page.waitForTimeout(2000)
    const names = await page.locator('.legend-name').allTextContents()
    expect(names.sort()).toEqual(
      ['Crocodile', 'Elephant', 'Giraffe', 'Lion', 'Monkey', 'Pawn', 'Superpawn', 'Zebra'])
    // No standard chess pieces: Congo has none, and the engine's default
    // promotion choices used to leak four of them into the list.
    expect(names).not.toContain('Queen')
    expect(names).not.toContain('Knight')
    const dots = await page.locator('.legend-target').count()
    expect(dots).toBeGreaterThan(50)
  })

  test('shows a piece once per region when its moves depend on where it stands', async ({ page }) => {
    await page.goto(`${BASE}?family=chess&variant=congo&opponent=human`)
    await page.waitForSelector('#game-play-root [data-sq]', { timeout: 20000 })
    await page.waitForTimeout(2000)
    const croc = page.locator('.legend-row').filter({ has: page.locator('.legend-name', { hasText: 'Crocodile' }) })
    await expect(croc.locator('.legend-board')).toHaveCount(3)
    const regions = await croc.locator('.legend-region').allTextContents()
    expect(regions.sort()).toEqual(['north bank', 'river', 'south bank'])
  })

  test('works for a family that is not chess', async ({ page }) => {
    await page.goto(`${BASE}?family=shogi&variant=standard&opponent=human`)
    await page.waitForSelector('#game-play-root [data-sq]', { timeout: 20000 })
    await page.waitForTimeout(2000)
    expect(await page.locator('.legend-row').count()).toBeGreaterThan(4)
    expect(await page.locator('.legend-target').count()).toBeGreaterThan(20)
  })
})
