export { standard } from './standard.js'
export { noCastling } from './no-castling.js'
export { torpedo } from './torpedo.js'
export { threeCheck } from './three-check.js'
export { fiveCheck } from './five-check.js'
export { kingOfTheHill } from './king-of-the-hill.js'
export { racingKings } from './racing-kings.js'
export { antichess } from './antichess.js'
export { capablanca } from './capablanca.js'
export { losAlamos } from './los-alamos.js'
export { horde } from './horde.js'
export { stalemateWins } from './stalemate-wins.js'
export { checklessChess } from './checkless-chess.js'
export { extinction, singleCheck, codrus, omnicide, breakthrough, shatar } from './win-condition.js'
export { giveaway, suicideChess, noRetreat, patrolChess, makpong } from './filter-variants.js'
