// Landing pages for the playable families, built from the rules corpus.
//
// The first ten families were given pages written by hand, and every family
// that became playable after them had none: the homepage linked the new ones
// to the play page, and some it did not list at all. A page for each family is
// generated here from what the corpus already says - the rulebook's title,
// tagline and how-to-play, a variant's own description and engine block - so
// a family has a page the day it becomes playable.
//
// A hand-written page is left alone. A generated page carries GENERATED_MARK
// and is rewritten on every run, so it cannot drift from the corpus.

import fs from 'fs'
import path from 'path'
import { parseFrontmatter } from '../../packages/schema/src/parse-frontmatter.js'
import { serializeFrontmatter } from '../../packages/schema/src/serialize-frontmatter.js'

export const GENERATED_MARK = '<!-- Generated by scripts/build-discovery.mjs from the rules corpus. Edits here are overwritten. -->'

const RULES_SITE = 'https://rules.moddable.games/'
const CODE_LINES = 26
const CODE_WIDTH = 96

const escapeHtml = (text) => String(text ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

// Markdown emphasis and links read as plain text on a card.
const plain = (text) => String(text ?? '').replace(/\*\*?([^*]+)\*\*?/g, '$1').replace(/\[([^\]]+)\]\([^)]*\)/g, '$1').trim()

// A rulebook's tagline is a phrase with no full stop, and the lede and the
// meta description set a sentence after it: without one, Chaupar's read
// "split throws Team race game".
const sentence = (text) => (!text || /[.!?]$/.test(text) ? text : text + '.')

function readMeta(file) {
  if (!file || !fs.existsSync(file)) return {}
  return parseFrontmatter(fs.readFileSync(file, 'utf8')).meta || {}
}

// A variant's own first paragraph of prose, skipping headings, diagrams,
// tables and markup.
function firstParagraph(file) {
  if (!file || !fs.existsSync(file)) return ''
  const body = parseFrontmatter(fs.readFileSync(file, 'utf8')).body || ''
  for (const block of body.split(/\n\s*\n/)) {
    const text = block.trim()
    if (!text || /^(#|\{\{|\||<|-|\*\*[^*]+:\*\*)/.test(text)) continue
    return text.replace(/\s+/g, ' ')
  }
  return ''
}

// Where a variant's file is: a board game's under content/variants, a
// component game's wherever the manifest records it.
function variantFile(rulesRoot, entry) {
  const slug = entry.slug || entry.variant
  return entry.path
    ? path.join(rulesRoot, entry.family, entry.path)
    : path.join(rulesRoot, entry.family, 'content', 'variants', `${slug}.md`)
}

// The part of the frontmatter that makes the game: the board, the seats, the
// plugin that plays it and the keys it reads, from the rulebook and the
// variant together. Long lists are cut, because the point is the shape.
function engineExcerpt(family, rulebookEngine, variantEngine) {
  // The variant's own keys first, then what it inherits from the rulebook;
  // the vocabulary is how pieces are written, not how the game is played.
  const pluginBlock = { ...(variantEngine.plugins?.[family] || {}) }
  for (const [key, value] of Object.entries(rulebookEngine.plugins?.[family] || {})) {
    if (!(key in pluginBlock)) pluginBlock[key] = value
  }
  delete pluginBlock.vocabulary
  const engine = {}
  const topology = variantEngine.topology || rulebookEngine.topology
  if (topology) engine.topology = topology
  const players = variantEngine.players || rulebookEngine.players
  if (players) engine.players = players
  const host = variantEngine.plugin || rulebookEngine.plugin
  if (host) engine.plugin = host
  if (Object.keys(pluginBlock).length) engine.plugins = { [family]: pluginBlock }
  const text = serializeFrontmatter({ engine }).replace(/^---\n/, '').replace(/\n---\s*$/, '')
  const lines = text.split('\n').map(line => (line.length > CODE_WIDTH ? line.slice(0, CODE_WIDTH - 1) + '…' : line))
  return lines.length > CODE_LINES ? [...lines.slice(0, CODE_LINES), '  # …'].join('\n') : lines.join('\n')
}

// The variants a page shows: the standard form first, then the next in turn.
function showcaseEntries(entries) {
  const ordered = [...entries].sort((a, b) => {
    const rank = (e) => ((e.slug || e.variant) === 'standard' ? 0 : 1)
    return rank(a) - rank(b)
  })
  return ordered.slice(0, 2)
}

function rulesLink(boardIndex, family, slug) {
  const entry = boardIndex.find(b => b.family === family && (b.playAs === slug || b.variant === slug))
  if (!entry || !entry.rulesUrl) return null
  return RULES_SITE + entry.rulesUrl.replace(/index\.html$/, '')
}

// A footer column as long as the others: the largest families, then a link
// to the page that lists them all. Every family in the column made it two or
// three times the height of its neighbours.
const FOOTER_FAMILIES = 8

function footerFamilies(pages, prefix, counts = {}) {
  const largest = [...pages]
    .sort((a, b) => (counts[b.family] || 0) - (counts[a.family] || 0) || a.label.localeCompare(b.label))
    .slice(0, FOOTER_FAMILIES)
  return [
    ...largest.map(p => `        <a href="${prefix}${p.family}/">${escapeHtml(p.label)}</a>`),
    `        <a href="${prefix}">All ${pages.length} families</a>`,
  ].join('\n')
}

export function buildFamilyPages({ root, rulesRoot, manifest, boardIndex, version, symbols, docs = {} }) {
  const playable = manifest.filter(e => e.playable)
  const families = [...new Set(playable.map(e => e.family))]
  const labels = {}
  for (const e of playable) if (!labels[e.family]) labels[e.family] = e.familyLabel || e.family
  const pages = families.map(family => ({ family, label: labels[family] }))
  const counts = {}
  for (const e of playable) counts[e.family] = (counts[e.family] || 0) + 1
  const outputs = []

  for (const family of families) {
    const file = path.join(root, 'families', family, 'index.html')
    const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null
    if (existing && !existing.includes(GENERATED_MARK)) continue

    const entries = playable.filter(e => e.family === family)
    const rulebook = readMeta(path.join(rulesRoot, family, 'content', 'rulebook.md'))
    const label = labels[family]
    const symbol = symbols[family] || '&#x25C6;'
    const tagline = plain(rulebook.tagline || '')
    const howToPlay = plain(rulebook.how_to_play || '')
    const description = `${label}: ${entries.length} playable variant${entries.length === 1 ? '' : 's'} from one engine. ${sentence(tagline)}`.trim()
    const host = rulebook.engine?.plugin || family

    const showcases = showcaseEntries(entries).map(entry => {
      const slug = entry.slug || entry.variant
      const meta = readMeta(variantFile(rulesRoot, entry))
      const code = engineExcerpt(family, rulebook.engine || {}, meta.engine || {})
      const rules = rulesLink(boardIndex, family, slug)
      const blurb = plain(meta.special || meta.description || firstParagraph(variantFile(rulesRoot, entry)) || meta.win || howToPlay || tagline)
      const title = meta.title || entry.label || slug
      return `  <div class="showcase-pair">
    <div class="showcase-code">
      <h3>${escapeHtml(title)}${rules ? ` <a href="${rules}" class="rules-link" target="_blank" rel="noopener">Rules</a>` : ''}</h3>
      <p class="showcase-desc">${escapeHtml(blurb)}</p>
      <pre><code>${escapeHtml(code)}</code></pre>
    </div>
    <div class="showcase-board">
      <iframe src="../../play/?embed=1&amp;family=${family}&amp;variant=${slug}" loading="lazy" title="${escapeHtml(title)}"></iframe>
      <p class="board-caption">${escapeHtml(title)}</p>
    </div>
  </div>`
    }).join('\n\n')

    const hasBoards = boardIndex.some(b => b.family === family)
    const url = `https://engine.moddable.games/families/${family}/`
    const content = `<!doctype html>
${GENERATED_MARK}
<html lang="en" data-family="${family}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(label)} — Moddable Engine</title>
<meta name="description" content="${escapeHtml(description)}">
<meta property="og:title" content="${escapeHtml(label)} — Moddable Engine">
<meta property="og:description" content="${escapeHtml(description)}">
<meta property="og:image" content="https://engine.moddable.games/og/homepage.png?v=${version}">
<meta property="og:url" content="${url}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Moddable Engine">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${escapeHtml(label)} — Moddable Engine">
<meta name="twitter:description" content="${escapeHtml(description)}">
<meta name="twitter:image" content="https://engine.moddable.games/og/homepage.png?v=${version}">
<meta name="theme-color" content="#0a0d2a">
<link rel="icon" type="image/svg+xml" href="../../favicon.svg">
<link rel="stylesheet" href="../../css/families.css?v=${version}">
</head>
<body>

<header class="site-header">
  <div class="header-inner">
    <a href="../../" class="header-brand">
      <span class="brand-icon">&#x2B22;</span>
      <span class="brand-text">moddable<span class="brand-accent">.engine</span></span>
    </a>
    <nav class="header-nav">
      <a href="../../play/" class="nav-link">Play</a>
      <a href="../../create/" class="nav-link">Create</a>
      <a href="../../boards/" class="nav-link">Boards</a>
      <a href="../../pieces/" class="nav-link">Pieces</a>
      <a href="../../tiles/" class="nav-link">Tiles</a>
      <a href="../../docs/" class="nav-link">Docs</a>
      <a href="../../api/" class="nav-link">API</a>
      <a href="https://github.com/Moddable-Games/moddable-engine" class="nav-link nav-link--gh" target="_blank" rel="noopener">GitHub</a>
    </nav>
    <button class="nav-toggle" aria-label="Toggle navigation"><span></span><span></span><span></span></button>
  </div>
</header>

<section class="family-hero">
  <div class="family-hero-inner">
    <span class="hero-symbol">${symbol}</span>
    <h1>${escapeHtml(label)}</h1>
    <p class="hero-lede">${escapeHtml(howToPlay ? sentence(tagline) : tagline)}${howToPlay ? ' ' + escapeHtml(howToPlay) : ''}</p>
    <div class="hero-meta">
      <div class="hero-meta-item">
        <span class="hero-meta-value" data-stat="variants">${entries.length}</span>
        <span class="hero-meta-label">Variants</span>
      </div>
      <div class="hero-meta-item">
        <span class="hero-meta-value">${escapeHtml(host)}</span>
        <span class="hero-meta-label">Plugin</span>
      </div>
      <div class="hero-meta-item">
        <span class="hero-meta-value">&#x2713;</span>
        <span class="hero-meta-label">Frontmatter-only</span>
      </div>
    </div>
  </div>
</section>

<section class="showcase">
  <div class="showcase-intro">
    <h2>Declared, Not Coded</h2>
    <p>Every rule of ${escapeHtml(label)} below is frontmatter in the rules corpus${host !== family ? `, played by the ${escapeHtml(host)} plugin` : ''}. The board beside each is the game itself, live.</p>
  </div>

${showcases}
</section>

<section class="family-cta">
  <h2>Play All <span data-stat="variants">${entries.length}</span> Variant${entries.length === 1 ? '' : 's'}</h2>
  <p>Every ${escapeHtml(label)} variant is playable against the AI or another player.</p>
  <div class="cta-actions">
    <a href="../../play/?family=${family}" class="btn btn--primary">Play ${escapeHtml(label)}</a>
    ${hasBoards ? `<a href="../../boards/?family=${family}" class="btn btn--ghost">Browse Boards</a>` : `<a href="../../create/" class="btn btn--ghost">Create a Variant</a>`}
    <a href="${docs[family] || '../../docs/sdk.html'}" class="btn btn--ghost">SDK Docs</a>
  </div>
</section>

<footer class="site-footer">
  <div class="footer-inner">
    <div class="footer-columns">
      <div class="footer-col">
        <h4 class="footer-heading">Engine</h4>
        <a href="../../play/">Play</a>
        <a href="../../boards/">Boards</a>
        <a href="../../pieces/">Pieces</a>
        <a href="../../tiles/">Tiles</a>
        <a href="../../docs/">Docs</a>
        <a href="../../api/">API</a>
      </div>
      <div class="footer-col">
        <h4 class="footer-heading">Families</h4>
${footerFamilies(pages, '../', counts)}
      </div>
      <div class="footer-col">
        <h4 class="footer-heading">Source</h4>
        <a href="https://github.com/Moddable-Games/moddable-engine" target="_blank" rel="noopener">GitHub</a>
        <a href="https://github.com/Moddable-Games/moddable-rules" target="_blank" rel="noopener">Rules Repo</a>
      </div>
    </div>
    <div class="footer-bottom">
      <span>&copy; 2012&ndash;2026 Moddable Games. MIT License.</span>
      <span class="footer-version">v${version}</span>
    </div>
  </div>
</footer>

<script src="../../js/families.js?v=${version}"></script>
<script src="../../js/site-nav.js?v=${version}"></script>
</body>
</html>
`
    outputs.push({ path: `families/${family}/index.html`, content })
  }

  return { outputs, pages, labels, counts }
}

// The homepage's family chips: every playable family, each linking to its
// landing page, with its variant count.
export function familyChips(pages, counts, symbols) {
  const ordered = [...pages].sort((a, b) => (counts[b.family] || 0) - (counts[a.family] || 0) || a.label.localeCompare(b.label))
  return ordered.map(({ family, label }) =>
    `      <a href="families/${family}/" class="family-chip"><span class="family-symbol">${symbols[family] || '&#x25C6;'}</span> ${escapeHtml(label)} <span class="family-count">${counts[family] || 0}</span></a>`).join('\n')
}

// The Families column of a page footer, for the hand-written pages too.
export function footerFamiliesColumn(pages, prefix, counts) {
  return `<h4 class="footer-heading">Families</h4>\n${footerFamilies(pages, prefix, counts)}\n      </div>`
}

// families/: every playable family, as the homepage shows them, with the
// footer the family pages share.
export function familiesIndex({ pages, counts, symbols, version, template }) {
  const chips = familyChips(pages, counts, symbols).replace(/href="families\//g, 'href="')
  const hero = `<section class="family-hero">
  <div class="family-hero-inner">
    <span class="hero-symbol">&#x25C6;</span>
    <h1>Playable Families</h1>
    <p class="hero-lede">Every family the engine plays, each with its own page: the rules it declares, its variants live, and how to embed them.</p>
  </div>
</section>

<section class="showcase">
  <div class="family-grid">
${chips}
  </div>
</section>

`
  const head = template.slice(0, template.indexOf('<section class="family-hero">'))
    .replace(/<title>[^<]*<\/title>/, '<title>Playable Families — Moddable Engine</title>')
    .replace(/(content=")[^"]*( — Moddable Engine")/g, '$1Playable Families$2')
    .replace(/(<meta (?:name|property)="(?:og:|twitter:)?description" content=")[^"]*(")/g, `$1${pages.length} playable families from one engine, each with its own page.$2`)
    .replace(/families\/[a-z0-9-]+\/"/, 'families/"')
    .replace(/ data-family="[^"]*"/, '')
    .replace(/\.\.\/\.\.\//g, '../')
  const foot = template.slice(template.indexOf('<footer class="site-footer">'))
    .replace(/\.\.\/\.\.\//g, '../')
    .replace(/<h4 class="footer-heading">Families<\/h4>[\s\S]*?<\/div>/, `<h4 class="footer-heading">Families</h4>\n${footerFamilies(pages, './', counts)}\n      </div>`)
    .replace(/<script src="\.\.\/js\/families\.js[^>]*><\/script>\n?/, '')
  return { path: 'families/index.html', content: head + hero + foot }
}
