export { getDeckConfig, getRegisteredDecks, getAllDecks } from './deck-registry.js'
export { createDeck, shuffle, deal } from './deck-ops.js'
export { layoutHand, layoutTable } from './layout.js'

import './decks/standard-52.js'
import './decks/bavarian-32.js'
import './decks/hanafuda-48.js'
import './decks/mahjong-136.js'
import './decks/dominoes-28.js'
import './decks/standard-dice.js'
